### ISSUE TITLE
The team pirates appear as "Pires"

### ISSUE THREAD

**Issue by sciencekidster** [baer/isThereAFuckingGame#11]
<img width="1440" alt="screen shot 2015-09-22 at 10 34 13 am" src="https://cloud.githubusercontent.com/assets/7388349/10024662/82856594-6115-11e5-9ef8-82d8987d9458.png">

**Comment by baer** [comment]
Oh noes! This is actually a problem with the data but it's easy enough to fix. I'l look into this tonight. Thanks for the report.

**Comment by baer** [comment]
Ugh, I was hoping the 2016 data would be fixed but it's not.

**Comment by baer** [comment]
Corrected and pushed.
