### ISSUE TITLE
Today's game information appears wrong

### ISSUE THREAD

**Issue by sam-huckaby** [baer/isThereAFuckingGame#13]
I expect this is a data-related issue, but I pulled up the site today and it says the Rockies are playing an away game at noon, when it's actually a home game at 2:10.

Feel free to close this out whenever, I just wanted to bring it up.

**Comment by alexweltman** [comment]
For me it says the game is at midnight. I'm guessing the time is coming through as 0 or undefined?

**Comment by watsoncj** [comment]
sup, @baer, this should get the site displaying correct info for now.

Longer term, I like the approach of the iso date-time in the schedule.json. 

:baseball:

**Comment by baer** [comment]
I just merged and deployed #14 which should fix this.
