### ISSUE TITLE
JS error in production!

### ISSUE THREAD

**Issue by creatifyme** [baer/isThereAFuckingGame#18]
Website is getting a JS error preventing me to know if there is a F***** ROCKIES GAME! Thanks for maintaining this repo! I use this site every baseball season to avoid downtown.

`Cannot read property 'location' of undefined`

**Comment by baer** [comment]
Sorry for the delay buuuuut, I've pretty much completely rewritten the site and it's back online. Sorry for the disruption (both mine and, the Rockies 😄). If you notice anything else, just drop me a line.
