### ISSUE TITLE
Not showing today's game

### ISSUE THREAD

**Issue by thepaulfox** [baer/isThereAFuckingGame#19]
Today is April 12. There is a home game today against the Padres. However, the site says the next game is tomorrow. 

I did check, and the game shows up in the schedule file that you updated 5 days ago. The date format did change when you changed the schedule, so not sure if there's a time zone issue. Sorry haven't had time to look further into the code.

![image](https://cloud.githubusercontent.com/assets/31291/24976422/a1954c70-1f86-11e7-9e8b-635f5aef91ed.png)

**Comment by baer** [comment]
Thanks for opening this issue! Sorry for the delay here. The site is now back online and is almost completely rewritten. Everything should be working as expected now. If there are any other things you notice, just drop me a line. I'm deep in it atm.
