### ISSUE TITLE
When a game has started, the website reverts to "NO"

### ISSUE THREAD

**Issue by doodlebro** [baer/isThereAFuckingGame#22]
Currently, there is a Rockies game in progress, however the site says there is not a rockies game today and gives tomorrow's game schedule.

Best fix is to account for games in progress. If the game has started but not yet finished, the site should still say YES with the game in progress displayed.

**Comment by mmindenhall** [comment]
I just noticed the same behavior.  I think that the site should say YES before, during, or after the game scheduled on that day (using the local team timezone).  Perhaps after the game has started, the answer is YES, and if there's also a game the next day, it is also shown?

**Comment by baer** [comment]
Sorry for the delay! This project is back online and was almost completely rewritten. There was a game today but it's already over and the behavior seems to be correct now. Let me know if you run into anything else. I'm deep in it atm :). Also, thanks for creating the issue!
