### ISSUE TITLE
Broken for 2019

### ISSUE THREAD

**Issue by iarry** [baer/isThereAFuckingGame#23]

**Comment by bbonet-entercom** [comment]
He moved to Seattle and retired it a year or two ago. Maybe one of the forks are maintaining it?

**Comment by bbonet-entercom** [comment]
Maybe you're the person to take it on!

**Comment by pennstatephil** [comment]
I've submitted a PR https://github.com/baer/isThereAFuckingGame/pull/24

**Comment by baer** [comment]
Y'all. I'm so sorry but Github didn't send me notifications!!!!!!

Thanks to @pennstatephil, this is all sorted out

https://www.isthereafuckingrockiesgame.com/

💥
