### ISSUE TITLE
Next game info is weird

### ISSUE THREAD

**Issue by pennstatephil** [baer/isThereAFuckingGame#25]
Despite the data update-- something is messing with the next game (it's 4/10 today):

> Rockies vs. the fucking Brewers
> Sunday, Sep 29, 2019 1:10 pm @ Coors Field - Denver

Suspect something is up with either the server time or the library being used to determine the date for the next game. (@baer just wanna make sure you see this since you didn't get a notif before!)

**Comment by pennstatephil** [comment]
update-- determined next game is correct on firefox, but not chrome or safari.

**Comment by baer** [comment]
Thanks for the @mention. For whatever reason, I always get those. I'll have a look, thanks.

**Comment by pennstatephil** [comment]
Also confirmed that it's impacting the current game as well as the next game (i.e. firefox shows there is an away game today, chrome says there is no game)

**Comment by pennstatephil** [comment]
@baer fix is ready to merge, check out #26 please
