### ISSUE TITLE
Webkit browsers not showing today's game

### ISSUE THREAD

**Issue by squid314** [baer/isThereAFuckingGame#27]
Webkit-based browsers are not showing the correct game information. Currently stating that there is no game today (incorrect) and that the next game is the last game of the season. Tested this in desktop Chrome 74, Safari 12.1.1, and Opera 60.0 where it fails. Tested in desktop Firefox 67.0 where it shows the correct information. Also tested Android Chrome and Firefox with the same results. No errors are shown in the console.

**Comment by squid314** [comment]
I just noticed @pennstatephil's commit. is this just not deployed yet?

**Comment by pennstatephil** [comment]
it was merged, but it didn't appear to update on the site. I don't know the innerworkings of the project, so I'm guessing deployment is manual, or something like that. @baer may have insight?

**Comment by baer** [comment]
Sorry about the disruption but, this project is back online and almost completely rewritten. Things look to be rendering properly now. Deployments are now handled by GH Actions => Cloudflare :)
