### ISSUE TITLE
Willing to take over the site if necessary

### ISSUE THREAD

**Issue by arjunsharma** [baer/isThereAFuckingGame#5]
One of my coworkers sent me a link to this tweet: https://twitter.com/michelesliger/status/586521797660647424

If you're looking for a new maintainer of the Rockies site I'd be happy to carry the torch. I live and work next to Coors Field, so the site actually provides a valuable service to me and my coworkers.

- Arjun

**Comment by baer** [comment]
Hey Arjun! First, holy crap! I can't believe github didn't notify me of your message! Im so sorry it has taken so long to respond. I'm so glad the site has been useful to you. Is there something specific that it's missing right now? I'm on a climbing trip for the rest of the week but I'm happy to respond to issues and/or suggestions. I'm 2/3 getting it onto gulp+webpack now and next up is a node based csv importer.

**Comment by arjunsharma** [comment]
Hey there! Sorry for the delay, I didn't see that you had replied.

I didn't have any specific code feedback, someone had pointed out that the site hadn't been updated for the new season at the time, so I was volunteering to help out with the deployment if need be. I saw that the site got updated with the 2015 schedule, so it's a non-issue.

Awesome little project by the way!
