### ISSUE TITLE
Convert EDT time into Mountain Time

### ISSUE THREAD

**Issue by baer** [baer/isThereAFuckingGame#9]
use moment-timezone to figure out how to convert the games to mountain time.

**Comment by bbonet-levelsbeyond** [comment]
Dude. You're a monster.

**Comment by baer** [comment]
It turns out that EDT (what the MLB uses) is not a unique timezone. It also specifically does not obey daylight savings time so it's been a little trickier than I thought. 

@bbonet-levelsbeyond is this your fork? I am about to do a huge rev which will have dramatically better mobile perf. Just an FYI, it's mostly done and will get merged to master in the next day or two.
https://github.com/bbonet/isThereAFuckingGame

**Comment by bbonet** [comment]
I'm just commenting on your general activity. ;-)  Of course, this is the
problem with trying to auto ingest the schedule. When I did
isthereafuckingavsgame it was a bit different, so it wouldn't surprise me
that the schema could change on a whim. Granted that risk is once per
season.

**Comment by baer** [comment]
Sorry for the delay but, I've done an almost-complete rewrite and I'm using `moment-tz` to handle it. I know, I know I should be using Luxon or date-fns, or some other lib that takes advantage of `Intl` but, Moment was what I had in that moment (get it!). The relevant code is in the Schedule converter and it's a bit ugly but, it'll do. PRs welcome. Not sure yet if this breaks based on DST but, we'll see.

Let's just all prey that the [[Sunshine Protection Act of 2021](https://www.congress.gov/bill/117th-congress/senate-bill/623/text)](https://www.congress.gov/bill/117th-congress/senate-bill/623/text) finally gets written into law and all this silliness can be over. 

```
    const date = moment.tz(
      `${game["START DATE"]} ${game["START TIME ET"]}`,
      "MM/DD/YY hh:mm a",
      "America/New_York"
    );
```
